### ISSUE TITLE
opencv windowsでうまいこと動かない

### ISSUE THREAD

**Issue by taiki-nakaso** [taiki-nakaso/bottle-detection#4]
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\*****...*****\bottle-detection\keras-yolo3\yolo.py", line 207, in detect_video
    cv2.namedWindow("result", cv2.WINDOW_NORMAL)
cv2.error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\highgui\src\window.cpp:634: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvNamedWindow'
```
わからない

**Comment by taiki-nakaso** [comment]
使わない！
